export const addPastTrainings = 'ADD_PAST_TRAINING'
export const addCurrentTraining = 'ADD_CURRENT_TRAINING'
export const deleteCurrentTraining = 'DELETE_CURRENT_TRAINING'
export const editCurrentTraining = 'EDIT_CURRENT_TRAINING'
export const changeTrainingsInRow = 'CHANGE_TRAININGS_IN_ROW'
export const setPastTrainings = 'SET_PAST_TRAININGS'
export const setCurrentTrainings = 'SET_CURRENT_TRAININGS'
